/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/register/auth': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Adds a booker entry for a user authorised on GOV.UK one login if it does not exist and / or returns the booker reference for the booker.
     * @description Creates a booker to allow access to public visits  if it does not exist and / or returns the booker reference for the given auth details.
     */
    put: operations['bookerAuthorisation']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Validates a prisoner's details against prisoner search and adds the prisoner against the prisoner if valid
     * @description Validates a prisoner's details against prisoner search and adds the prisoner against the prisoner if valid
     */
    put: operations['registerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Create booker prisoner details
     * @description Create booker prisoner details
     */
    put: operations['createBookerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Create booker prisoner visitor details
     * @description Create booker prisoner visitor details
     */
    put: operations['createBookerPrisonerVisitor']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor/{visitorId}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * deactivate booker prisoner visitor
     * @description deactivate booker prisoner visitor
     */
    put: operations['deactivateBookerPrisonerVisitor']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor/{visitorId}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * activate booker prisoner visitor
     * @description activate booker prisoner visitor
     */
    put: operations['activateBookerPrisonerVisitor']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/prison': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update a registered prisoner's prison code
     * @description Update a registered prisoner's prison code
     */
    put: operations['updateBookerPrisonerPrison']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * deactivate booker prisoner
     * @description deactivate booker prisoners
     */
    put: operations['deactivateBookerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * activate booker prisoner
     * @description activate booker prisoner
     */
    put: operations['activateBookerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/permitted/visitors/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit a request to add a visitor to a booker's prisoner permitted visitor list
     * @description Submit a request to add a visitor to a booker's prisoner permitted visitor list
     */
    post: operations['submitRequestAddVisitorToBookerPrisoner']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Search for a booker using specific criteria
     * @description Search for a booker using specific criteria, returns list (list of 1 entry if only 1 booker is found)
     */
    post: operations['searchForBooker']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/visitors/requests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all active visitor requests for a booker
     * @description Get all active visitor requests for a booker
     */
    get: operations['getActiveVisitorRequests']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get permitted prisoners associated with a booker.
     * @description Get permitted prisoners associated with a booker.
     */
    get: operations['getPermittedPrisonersForBooker']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Validates a prisoner for whom the booker is about to book a visit
     * @description Validates a prisoner for whom the booker is about to book a visit
     */
    get: operations['validatePrisonerBeforeBooking']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/permitted/visitors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get permitted visitors for a permitted prisoner associated with that booker.
     * @description Get permitted visitors for a permitted prisoner associated with that booker.
     */
    get: operations['getPermittedVisitorsForPrisoner']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/audit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a booker's audit information
     * @description Get a booker's audit information
     */
    get: operations['getBookerAudit']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get bookers details using reference
     * @description gets bookers details
     */
    get: operations['getBookerDetailsUsingReference']
    put?: never
    post?: never
    /**
     * Clear bookers details
     * @description Clear bookers details, keeps booker reference and email
     */
    delete: operations['clearBookerDetails']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor/{visitorId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * unlink booker prisoner visitor
     * @description unlink booker prisoner visitor
     */
    delete: operations['unlinkBookerPrisonerVisitor']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ErrorResponseDto: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Auth detail Dto */
    AuthDetailDto: {
      /** @description auth reference/sub */
      oneLoginSub: string
      /** @description auth email */
      email: string
      /** @description auth phone number */
      phoneNumber?: string
    }
    /** @description Booker reference Object, to be used with all other api call for booker information */
    BookerReference: {
      /** @description This value is the booker reference and should be used to acquire booker information */
      value: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Details to register a prisoner to a booker. */
    RegisterPrisonerRequestDto: {
      /**
       * @description Prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description Prisoner first name
       * @example James
       */
      prisonerFirstName: string
      /**
       * @description Prisoner last name
       * @example Smith
       */
      prisonerLastName: string
      /**
       * Format: date
       * @description Prisoner date of birth
       * @example 1960-01-30
       */
      prisonerDateOfBirth: string
      /**
       * @description Prison Id
       * @example MDI
       */
      prisonId: string
    }
    /** @description Create permitted prisoner with permitted visitors associated with the booker. */
    CreatePermittedPrisonerDto: {
      /**
       * @description prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description prison code
       * @example MDI
       */
      prisonCode: string
    }
    /** @description Permitted prisoner associated with the booker. */
    PermittedPrisonerDto: {
      /**
       * @description prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description prison code
       * @example MDI
       */
      prisonCode: string
      /** @description Permitted visitors */
      permittedVisitors: components['schemas']['PermittedVisitorDto'][]
    }
    /** @description Permitted visitor associated with the permitted prisoner. */
    PermittedVisitorDto: {
      /**
       * Format: int64
       * @description Identifier for this contact (Person in NOMIS)
       * @example 5871791
       */
      visitorId: number
    }
    /** @description Create permitted prisoner with permitted visitors associated with the booker. */
    CreatePermittedVisitorDto: {
      /**
       * Format: int64
       * @description Identifier for this contact (Person in NOMIS)
       * @example 5871791
       */
      visitorId: number
      /**
       * @description A flag (boolean), when set to true will send booker notification of visitor linking
       * @example true
       */
      sendNotificationFlag: boolean
    }
    /** @description Update a prisoner's prison code. */
    UpdateRegisteredPrisonersPrisonDto: {
      /**
       * @description Prison Id
       * @example MDI
       */
      prisonId: string
    }
    /** @description Visitor request details to add a visitor to a booker prisoner */
    AddVisitorToBookerPrisonerRequestDto: {
      /** @description First name of the visitor in request */
      firstName: string
      /** @description Last name of the visitor in request */
      lastName: string
      /**
       * Format: date
       * @description Date of birth of the visitor in request
       */
      dateOfBirth: string
    }
    BookerValidationErrorResponse: {
      validationError: string
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Booker of visits. */
    SearchBookerDto: {
      /** @description auth email */
      email: string
    }
    /** @description Booker of visits. */
    BookerDto: {
      /** @description This is the booker reference and should be used to acquire booker information */
      reference: string
      /** @description auth reference/sub */
      oneLoginSub: string
      /** @description auth email */
      email: string
      /** @description Permitted prisoners list */
      permittedPrisoners: components['schemas']['PermittedPrisonerDto'][]
      /**
       * Format: date-time
       * @description The time of booker account creation
       */
      createdTimestamp: string
    }
    BookerPrisonerVisitorRequestDto: {
      /**
       * @description Visitor Request reference
       * @example abc-def-ghi
       */
      reference: string
      /**
       * @description Booker reference
       * @example wwe-egg-wwf
       */
      bookerReference: string
      /**
       * @description Prisoner ID for whom visitor was requested
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description First Name, as entered on visitor request
       * @example John
       */
      firstName: string
      /**
       * @description Last Name, as entered on visitor request
       * @example Smith
       */
      lastName: string
      /**
       * Format: date
       * @description Date of birth, as entered on visitor request
       * @example 2000-01-01
       */
      dateOfBirth: string
      /**
       * @description Request status
       * @example REQUESTED
       * @enum {string}
       */
      status: 'REQUESTED' | 'APPROVED' | 'REJECTED'
    }
    /** @description Audit entry for booker. */
    BookerAuditDto: {
      /** @description Booker reference */
      reference: string
      /**
       * @description Audit Type
       * @example PRISONER_REGISTERED
       * @enum {string}
       */
      auditType:
        | 'BOOKER_CREATED'
        | 'PRISONER_REGISTERED'
        | 'VISITOR_ADDED_TO_PRISONER'
        | 'ACTIVATED_PRISONER'
        | 'DEACTIVATED_PRISONER'
        | 'ACTIVATED_VISITOR'
        | 'DEACTIVATED_VISITOR'
        | 'UNLINK_VISITOR'
        | 'CLEAR_BOOKER_DETAILS'
        | 'UPDATE_BOOKER_EMAIL'
        | 'REGISTER_PRISONER_SEARCH'
        | 'UPDATE_REGISTERED_PRISONER_PRISON'
        | 'VISITOR_REQUEST_SUBMITTED'
      /** @description Audit summary */
      text: string
      /**
       * Format: date-time
       * @description Timestamp of booker audit entry
       */
      createdTimestamp: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  bookerAuthorisation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AuthDetailDto']
      }
    }
    responses: {
      /** @description Booker successfully added and / or booker reference returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerReference']
        }
      }
      /** @description An error occurred whilst adding the booker. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  registerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterPrisonerRequestDto']
      }
    }
    responses: {
      /** @description Prisoner added against booker for booking visits. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to register a prisoner against a booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Register prisoner validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePermittedPrisonerDto']
      }
    }
    responses: {
      /** @description Have created booker prisoner correctly */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Incorrect request to access this endpoint */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description The booker does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  createBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonerId: string
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePermittedVisitorDto']
      }
    }
    responses: {
      /** @description Have created booker prisoner visitor correctly */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Incorrect request to access this endpoint */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description The booker or the booker prisoner does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  deactivateBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
        visitorId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have deactivated booker prisoner visitor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description visitor not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  activateBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
        visitorId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have activated booker prisoner visitor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Visitor not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  updateBookerPrisonerPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRegisteredPrisonersPrisonDto']
      }
    }
    responses: {
      /** @description Registered prisoner's prison code wasupdated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Validation failure, incorrect request to update registered prisoner's prison code */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description booker / prisoner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  deactivateBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have deactivated booker prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Prisoner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  activateBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have activated booker prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Prisoner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  submitRequestAddVisitorToBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddVisitorToBookerPrisonerRequestDto']
      }
    }
    responses: {
      /** @description Request submitted to add a visitor to a booker's prisoner permitted visitor list */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to submit a visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker / Prisoner not found for visitor request */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Visitor request validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerValidationErrorResponse']
        }
      }
    }
  }
  searchForBooker: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchBookerDto']
      }
    }
    responses: {
      /** @description Booker found via search */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto'][]
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to search for booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getActiveVisitorRequests: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns a booker's active visitor requests */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerPrisonerVisitorRequestDto'][]
        }
      }
      /** @description Incorrect request to get booker's active visitor requests */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get booker's awaiting visitor requests. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker not found for booker reference. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  getPermittedPrisonersForBooker: {
    parameters: {
      query?: {
        /**
         * @description Returns active / inactive permitted prisoners or returns all permitted prisoners if this parameter is not passed.
         * @example true
         */
        active?: boolean
      }
      header?: never
      path: {
        /**
         * @description Booker's unique reference.
         * @example A12345DC
         */
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returned permitted prisoners associated with a booker */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto'][]
        }
      }
      /** @description Incorrect request to get permitted prisoners associated with a booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get permitted prisoners associated with a booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  validatePrisonerBeforeBooking: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        /**
         * @description Prisoner Id for that needs to be validated.
         * @example A12345DC
         */
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Validation passed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to get permitted visitors for a prisoner associated with that booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Prisoner validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerValidationErrorResponse']
        }
      }
    }
  }
  getPermittedVisitorsForPrisoner: {
    parameters: {
      query?: {
        /**
         * @description Returns active / inactive permitted visitors for a permitted prisoner or returns all permitted visitors for the permitted prisoner if this parameter is not passed.
         * @example true
         */
        active?: boolean
      }
      header?: never
      path: {
        bookerReference: string
        /**
         * @description prisonerId Id for whom permitted visitors need to be returned.
         * @example A12345DC
         */
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returned permitted visitors for a permitted prisoner associated with that booker */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto'][]
        }
      }
      /** @description Incorrect request to get permitted visitors for a permitted prisoner associated with that booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get permitted visitors for a permitted prisoner associated with that booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getBookerAudit: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns a booker's audit information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerAuditDto'][]
        }
      }
      /** @description Incorrect request to get booker's audit information */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get booker's audit information */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The booker does not exist or has no audit history */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  getBookerDetailsUsingReference: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Booker details found and returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Booker not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  clearBookerDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have cleared the booker details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Booker not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  unlinkBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
        visitorId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully unlinked booker prisoner visitor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description visitor not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
}
