/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/visitor-requests/{requestReference}/withdraw': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Withdraw visitor request.
     * @description Withdraw a pending visitor request.
     */
    put: operations['withdrawVisitorRequest']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/visitor-requests/{requestReference}/reject': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Reject visitor request.
     * @description Reject a visitor request.
     */
    put: operations['rejectVisitorRequest']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/visitor-requests/{requestReference}/approve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Approve visitor request and link visitor to booker's prisoner.
     * @description Approve visitor request and link visitor to booker's prisoner.
     */
    put: operations['approveVisitorRequest']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/register/auth': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Adds a booker entry for a user authorised on GOV.UK one login if it does not exist and / or returns the booker reference for the booker.
     * @description Creates a booker to allow access to public visits  if it does not exist and / or returns the booker reference for the given auth details.
     */
    put: operations['bookerAuthorisation']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/prison': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update a permitted prisoner's registered prison code
     * @description Update a permitted prisoner's registered prison code
     */
    put: operations['updatePermittedPrisonerPrison']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Validates a prisoner's details against prisoner search and adds the prisoner against the prisoner if valid
     * @description Validates a prisoner's details against prisoner search and adds the prisoner against the prisoner if valid
     */
    put: operations['registerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Create booker prisoner details
     * @description Create booker prisoner details
     */
    put: operations['createBookerPrisoner']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Create booker prisoner visitor details
     * @description Create booker prisoner visitor details
     */
    put: operations['createBookerPrisonerVisitor']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/prison': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update a registered prisoner's prison code
     * @deprecated
     * @description Update a registered prisoner's prison code
     */
    put: operations['updateBookerPrisonerPrison']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/prisoner/merge': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Manually merge a prisoner number
     * @description Updates records from an old prisoner number to a new prisoner number.
     */
    post: operations['mergePrisoner']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/prisoner/merge/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Manually merge prisoner numbers in a batch
     * @description Processes each prisoner number merge in its own transaction.
     */
    post: operations['mergePrisoners']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/permitted/visitors/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit a request to add a visitor to a booker's prisoner permitted visitor list
     * @description Submit a request to add a visitor to a booker's prisoner permitted visitor list
     */
    post: operations['submitRequestAddVisitorToBookerPrisoner']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}/prisoner/{prisonerId}/visitor/{visitorId}/unlink': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * unlink booker prisoner visitor
     * @description unlink booker prisoner visitor
     */
    post: operations['unlinkBookerPrisonerVisitor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Search for a booker using specific criteria
     * @description Search for a booker using specific criteria, returns list (list of 1 entry if only 1 booker is found)
     */
    post: operations['searchForBooker']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/visitor-requests/{requestReference}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a single visitor request, given a request reference
     * @description Get a single visitor request, given a request reference
     */
    get: operations['getSingleVisitorRequest']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/visitors/requests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all active visitor requests for a booker
     * @description Get all active visitor requests for a booker
     */
    get: operations['getActiveVisitorRequests']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get permitted prisoners associated with a booker.
     * @description Get permitted prisoners associated with a booker.
     */
    get: operations['getPermittedPrisonersForBooker']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Validates a prisoner for whom the booker is about to book a visit
     * @description Validates a prisoner for whom the booker is about to book a visit
     */
    get: operations['validatePrisonerBeforeBooking']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/permitted/prisoners/{prisonerId}/permitted/visitors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get permitted visitors for a permitted prisoner associated with that booker.
     * @description Get permitted visitors for a permitted prisoner associated with that booker.
     */
    get: operations['getPermittedVisitorsForPrisoner']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/{bookerReference}/audit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a booker's audit information
     * @description Get a booker's audit information
     */
    get: operations['getBookerAudit']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/public/booker/config/{bookerReference}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get bookers details using reference
     * @description gets bookers details
     */
    get: operations['getBookerDetailsUsingReference']
    put?: never
    post?: never
    /**
     * Clear bookers details
     * @description Clear bookers details, keeps booker reference and email
     */
    delete: operations['clearBookerDetails']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prison/{prisonCode}/visitor-requests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a list of all active visitor requests for a prison via prison code
     * @description Get a list of all active visitor requests for a prison via prison code
     */
    get: operations['getVisitorRequestsByPrisonCode']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prison/{prisonCode}/visitor-requests/count': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a count of all visitor requests for a prison via prison code
     * @description Get a count of all visitor requests for a prison via prison code
     */
    get: operations['getVisitorRequestsCountByPrisonCode']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number | null
      userMessage?: string | null
      developerMessage?: string | null
      moreInfo?: string | null
    }
    WithdrawVisitorRequestDto: {
      /**
       * @description Reference of booker who rejected the visitor
       * @example ab-cd-ef-gh
       */
      bookerReference: string
    }
    PrisonVisitorRequestDto: {
      /**
       * @description Visitor Request reference
       * @example abc-def-ghi
       */
      reference: string
      /**
       * @description Booker reference
       * @example wwe-egg-wwf
       */
      bookerReference: string
      /**
       * @description Booker email
       * @example test@test.com
       */
      bookerEmail: string
      /**
       * @description Prisoner ID for whom visitor was requested
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description First Name, as entered on visitor request
       * @example John
       */
      firstName: string
      /**
       * @description Last Name, as entered on visitor request
       * @example Smith
       */
      lastName: string
      /**
       * Format: date
       * @description Date of birth, as entered on visitor request
       * @example 2000-01-01
       */
      dateOfBirth: string
      /**
       * Format: date
       * @description Date request was submitted
       * @example 2025-10-28
       */
      requestedOn: string
      /**
       * Format: int64
       * @description If approved, this field will contain the visitorId who was added to the booker prisoner
       * @example 123456
       */
      visitorId: number | null
      /**
       * @description If rejected, this field will contain the rejection reason
       * @example REJECTED
       * @enum {string|null}
       */
      rejectionReason: 'ALREADY_LINKED' | 'REJECT' | null
      /**
       * @description The current status of the request
       * @example REQUESTED
       * @enum {string}
       */
      status: 'REQUESTED' | 'APPROVED' | 'AUTO_APPROVED' | 'REJECTED' | 'WITHDRAWN'
      /**
       * @description The language in which your correspondence will be sent
       * @example en
       * @enum {string}
       */
      languagePreference: 'en' | 'cy'
    }
    RejectVisitorRequestDto: {
      /**
       * @description Rejection Reason type
       * @example ALREADY_LINKED
       * @enum {string}
       */
      rejectionReason: 'ALREADY_LINKED' | 'REJECT'
      /**
       * @description STAFF username who rejected the visitor
       * @example ABC123D
       */
      actionedBy: string
    }
    ApproveVisitorRequestDto: {
      /**
       * Format: int64
       * @description Identifier for this contact (Person in NOMIS)
       * @example 5871791
       */
      visitorId: number
      /**
       * @description STAFF username who approved the visitor
       * @example ABC123D
       */
      actionedBy: string
    }
    /** @description Auth detail Dto */
    AuthDetailDto: {
      /** @description auth reference/sub */
      oneLoginSub: string
      /** @description auth email */
      email: string
      /** @description auth phone number */
      phoneNumber?: string | null
    }
    /** @description Booker reference Object, to be used with all other api call for booker information */
    BookerReference: {
      /** @description This value is the booker reference and should be used to acquire booker information */
      value: string
    }
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    /** @description Update a prisoner's prison code. */
    UpdateRegisteredPrisonerPrisonDto: {
      /**
       * @description Prison Id
       * @example MDI
       */
      prisonId: string
    }
    /** @description Permitted prisoner associated with the booker. */
    PermittedPrisonerDto: {
      /**
       * @description prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description prison code
       * @example MDI
       */
      prisonCode: string
      /** @description Permitted visitors */
      permittedVisitors: components['schemas']['PermittedVisitorDto'][]
    }
    /** @description Permitted visitor associated with the permitted prisoner. */
    PermittedVisitorDto: {
      /**
       * Format: int64
       * @description Identifier for this contact (Person in NOMIS)
       * @example 5871791
       */
      visitorId: number
    }
    /** @description Details to register a prisoner to a booker. */
    RegisterPrisonerRequestDto: {
      /**
       * @description Prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description Prisoner first name
       * @example James
       */
      prisonerFirstName: string
      /**
       * @description Prisoner last name
       * @example Smith
       */
      prisonerLastName: string
      /**
       * Format: date
       * @description Prisoner date of birth
       * @example 1960-01-30
       */
      prisonerDateOfBirth: string
      /**
       * @description Prison Id
       * @example MDI
       */
      prisonId: string
    }
    /** @description Create permitted prisoner with permitted visitors associated with the booker. */
    CreatePermittedPrisonerDto: {
      /**
       * @description prisoner Id
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description prison code
       * @example MDI
       */
      prisonCode: string
    }
    /** @description Create permitted prisoner with permitted visitors associated with the booker. */
    CreatePermittedVisitorDto: {
      /**
       * Format: int64
       * @description Identifier for this contact (Person in NOMIS)
       * @example 5871791
       */
      visitorId: number
      /**
       * @description A flag (boolean), when set to true will send booker notification of visitor linking
       * @example true
       */
      sendNotificationFlag: boolean | null
      /**
       * @description STAFF username who registered the visitor
       * @example ABC123D
       */
      actionedBy: string
    }
    /** @description Prisoner merge request with old and new prisoner numbers. */
    PrisonerMergeRequestDto: {
      /**
       * @description Old prisoner number to replace.
       * @example A1234AA
       */
      oldPrisonerNumber: string
      /**
       * @description New prisoner number to update records to.
       * @example B1234BB
       */
      newPrisonerNumber: string
    }
    /** @description Batch prisoner merge request. */
    PrisonerMergeBatchRequestDto: {
      /** @description Prisoner merges to process. */
      prisonerMerges: components['schemas']['PrisonerMergeRequestDto'][]
    }
    /** @description Visitor request details to add a visitor to a booker prisoner */
    AddVisitorToBookerPrisonerRequestDto: {
      /** @description First name of the visitor in request */
      firstName: string
      /** @description Last name of the visitor in request */
      lastName: string
      /**
       * Format: date
       * @description Date of birth of the visitor in request
       */
      dateOfBirth: string
      /**
       * @description The language in which your correspondence will be sent
       * @default en
       * @enum {string}
       */
      languagePreference: 'en' | 'cy'
    }
    BookerValidationErrorResponse: {
      validationError: string
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number | null
      userMessage?: string | null
      developerMessage?: string | null
      moreInfo?: string | null
    }
    CreateVisitorRequestResponseDto: {
      /**
       * @description Reference of newly created visitor request
       * @example abc-def-ghi
       */
      reference: string
      /**
       * @description Status of newly created visitor request
       * @example AUTO_APPROVED
       * @enum {string}
       */
      status: 'REQUESTED' | 'APPROVED' | 'AUTO_APPROVED' | 'REJECTED' | 'WITHDRAWN'
      /**
       * @description Reference of booker who submitted the request
       * @example abc-def-ghi
       */
      bookerReference: string
      /**
       * @description The id of the booker's prisoner for the visitor request
       * @example AA123456
       */
      prisonerId: string
      /**
       * @description The registered prison code of the booker's prisoner for the visitor request
       * @example HEI
       */
      prisonId: string
      /**
       * Format: int64
       * @description Identifier for a matched contact (Person in NOMIS), NULL if an automatic match for the visitor request was not found
       */
      visitorId?: number | null
      /**
       * @description The language in which your correspondence will be sent
       * @example en
       * @enum {string}
       */
      languagePreference: 'en' | 'cy'
    }
    ActionedByDto: {
      /**
       * @description STAFF username
       * @example ABC123D
       */
      username: string
    }
    /** @description Booker of visits. */
    SearchBookerDto: {
      /** @description auth email */
      email: string
    }
    /** @description Booker of visits. */
    BookerDto: {
      /** @description This is the booker reference and should be used to acquire booker information */
      reference: string
      /** @description auth reference/sub */
      oneLoginSub: string | null
      /** @description auth email */
      email: string
      /** @description Permitted prisoners list */
      permittedPrisoners: components['schemas']['PermittedPrisonerDto'][]
      /**
       * Format: date-time
       * @description The time of booker account creation
       */
      createdTimestamp: string
    }
    DlqMessage: {
      body: {
        [key: string]: unknown
      }
      messageId: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    BookerPrisonerVisitorRequestDto: {
      /**
       * @description Visitor Request reference
       * @example abc-def-ghi
       */
      reference: string
      /**
       * @description Booker reference
       * @example wwe-egg-wwf
       */
      bookerReference: string
      /**
       * @description Prisoner ID for whom visitor was requested
       * @example A1234AA
       */
      prisonerId: string
      /**
       * @description First Name, as entered on visitor request
       * @example John
       */
      firstName: string
      /**
       * @description Last Name, as entered on visitor request
       * @example Smith
       */
      lastName: string
      /**
       * Format: date
       * @description Date of birth, as entered on visitor request
       * @example 2000-01-01
       */
      dateOfBirth: string
      /**
       * @description Request status
       * @example REQUESTED
       * @enum {string}
       */
      status: 'REQUESTED' | 'APPROVED' | 'AUTO_APPROVED' | 'REJECTED' | 'WITHDRAWN'
      /**
       * Format: date
       * @description Date when the visitor request was added
       * @example 2026-05-01
       */
      requestedOn: string
      /**
       * @description The language in which your correspondence will be sent
       * @example en
       * @enum {string}
       */
      languagePreference: 'en' | 'cy'
    }
    /** @description Audit entry for booker. */
    BookerAuditDto: {
      /** @description Booker reference */
      reference: string
      /**
       * @description Audit Type
       * @example PRISONER_REGISTERED
       * @enum {string}
       */
      auditType:
        | 'BOOKER_CREATED'
        | 'PRISONER_REGISTERED'
        | 'VISITOR_ADDED_TO_PRISONER'
        | 'VISITOR_REQUEST_APPROVED_FOR_PRISONER'
        | 'VISITOR_REQUEST_AUTO_APPROVED_FOR_PRISONER'
        | 'VISITOR_REQUEST_REJECTED_FOR_PRISONER'
        | 'VISITOR_REQUEST_WITHDRAWN_FOR_PRISONER'
        | 'ACTIVATED_PRISONER'
        | 'DEACTIVATED_PRISONER'
        | 'ACTIVATED_VISITOR'
        | 'DEACTIVATED_VISITOR'
        | 'UNLINK_VISITOR'
        | 'CLEAR_BOOKER_DETAILS'
        | 'UPDATE_BOOKER_EMAIL'
        | 'REGISTER_PRISONER_SEARCH'
        | 'UPDATE_REGISTERED_PRISONER_PRISON'
        | 'VISITOR_REQUEST_SUBMITTED'
      /** @description Audit summary */
      text: string
      /**
       * Format: date-time
       * @description Timestamp of booker audit entry
       */
      createdTimestamp: string
    }
    VisitorRequestsCountByPrisonCodeDto: {
      /**
       * Format: int32
       * @description Count of visitor requests for prison
       * @example 5
       */
      count: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  withdrawVisitorRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        requestReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WithdrawVisitorRequestDto']
      }
    }
    responses: {
      /** @description Visit request withdrawn, no visitor will be linked to booker's prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonVisitorRequestDto']
        }
      }
      /** @description Incorrect request to withdraw a pending visitor request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to withdraw visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Pending visitor request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  rejectVisitorRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        requestReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RejectVisitorRequestDto']
      }
    }
    responses: {
      /** @description Visit request rejected, no visitor linked to booker's prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonVisitorRequestDto']
        }
      }
      /** @description Incorrect request to reject visitor request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to reject visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker or visitor request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  approveVisitorRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        requestReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApproveVisitorRequestDto']
      }
    }
    responses: {
      /** @description Visit request approved and visitor linked to booker's prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonVisitorRequestDto']
        }
      }
      /** @description Incorrect request to approve visitor request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to approve visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker or visitor request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bookerAuthorisation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AuthDetailDto']
      }
    }
    responses: {
      /** @description Booker successfully added and / or booker reference returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerReference']
        }
      }
      /** @description An error occurred whilst adding the booker. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  updatePermittedPrisonerPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRegisteredPrisonerPrisonDto']
      }
    }
    responses: {
      /** @description Permitted prisoner's registered prison code was updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Validation failure, incorrect request to update permitted prisoner's registered prison code */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description booker / prisoner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  registerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterPrisonerRequestDto']
      }
    }
    responses: {
      /** @description Prisoner added against booker for booking visits. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to register a prisoner against a booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Register prisoner validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePermittedPrisonerDto']
      }
    }
    responses: {
      /** @description Have created booker prisoner correctly */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Incorrect request to access this endpoint */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The booker does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonerId: string
        bookerReference: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePermittedVisitorDto']
      }
    }
    responses: {
      /** @description Have created booker prisoner visitor correctly */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto']
        }
      }
      /** @description Incorrect request to access this endpoint */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The booker or the booker prisoner does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  updateBookerPrisonerPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRegisteredPrisonerPrisonDto']
      }
    }
    responses: {
      /** @description Registered prisoner's prison code was updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto']
        }
      }
      /** @description Validation failure, incorrect request to update registered prisoner's prison code */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description booker / prisoner not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  mergePrisoner: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PrisonerMergeRequestDto']
      }
    }
    responses: {
      /** @description Prisoner number merge processed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to merge a prisoner number */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to merge a prisoner number */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  mergePrisoners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PrisonerMergeBatchRequestDto']
      }
    }
    responses: {
      /** @description Prisoner number merges processed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to merge prisoner numbers */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to merge prisoner numbers */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  submitRequestAddVisitorToBookerPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddVisitorToBookerPrisonerRequestDto']
      }
    }
    responses: {
      /** @description Request submitted to add a visitor to a booker's prisoner permitted visitor list */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateVisitorRequestResponseDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to submit a visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker / Prisoner not found for visitor request */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Visitor request validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerValidationErrorResponse']
        }
      }
    }
  }
  unlinkBookerPrisonerVisitor: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        prisonerId: string
        visitorId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActionedByDto']
      }
    }
    responses: {
      /** @description Successfully unlinked booker prisoner visitor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description visitor not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchForBooker: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchBookerDto']
      }
    }
    responses: {
      /** @description Booker found via search */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto'][]
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to search for booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getSingleVisitorRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        requestReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description single request successfully returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonVisitorRequestDto']
        }
      }
      /** @description Incorrect request to get a single visitor request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get a single visitor request */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker not found or visitor request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  getActiveVisitorRequests: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns a booker's active visitor requests */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerPrisonerVisitorRequestDto'][]
        }
      }
      /** @description Incorrect request to get booker's active visitor requests */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get booker's awaiting visitor requests. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker not found for booker reference. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPermittedPrisonersForBooker: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Booker's unique reference.
         * @example A12345DC
         */
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returned permitted prisoners associated with a booker */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedPrisonerDto'][]
        }
      }
      /** @description Incorrect request to get permitted prisoners associated with a booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get permitted prisoners associated with a booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  validatePrisonerBeforeBooking: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        /**
         * @description Prisoner Id for that needs to be validated.
         * @example A12345DC
         */
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Validation passed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Incorrect request to get permitted visitors for a prisoner associated with that booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Prisoner validation failed */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookerValidationErrorResponse']
        }
      }
    }
  }
  getPermittedVisitorsForPrisoner: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
        /**
         * @description prisonerId Id for whom permitted visitors need to be returned.
         * @example A12345DC
         */
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returned permitted visitors for a permitted prisoner associated with that booker */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PermittedVisitorDto'][]
        }
      }
      /** @description Incorrect request to get permitted visitors for a permitted prisoner associated with that booker */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get permitted visitors for a permitted prisoner associated with that booker */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getBookerAudit: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns a booker's audit information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerAuditDto'][]
        }
      }
      /** @description Incorrect request to get booker's audit information */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get booker's audit information */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The booker does not exist or has no audit history */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getBookerDetailsUsingReference: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Booker details found and returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  clearBookerDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        bookerReference: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Have cleared the booker details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BookerDto']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions for this action */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Booker not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getVisitorRequestsByPrisonCode: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description list successfully returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonVisitorRequestDto'][]
        }
      }
      /** @description Incorrect request to get list of active visitor requests for prison. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get list of active visitor requests for prison */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getVisitorRequestsCountByPrisonCode: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Count successfully returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VisitorRequestsCountByPrisonCodeDto']
        }
      }
      /** @description Incorrect request to get count of visitor requests for prison. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized to access this endpoint */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Incorrect permissions to get count of visitor requests for prison */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
